### ISSUE TITLE
Request for update of bluemonday dependency and new release 

### ISSUE THREAD

**Issue by miselico** [foolin/pagser#8]
I am working on a project which recursively depends on this one.
However, the latest release of this project depends on  github.com/microcosm-cc/bluemonday@v1.0.2 , while the version on master has a dependency on github.com/microcosm-cc/bluemonday@1.0.16. 

Would it be possible to create a new release, either from current master, or with an updated dependency to github.com/microcosm-cc/bluemonday@v1.0.26 ?

**Comment by foolin** [comment]
Latest version `0.1.6`:

https://github.com/foolin/pagser/releases/tag/v0.1.6

**Comment by miselico** [comment]
Thanks a million!
